### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by p2poolmining** [turtlecoin/turtlecoin-mobile-wallet#124]
I pulled a current copy of the **turtlecoin-mobile-wallet** from master and was able to compile the wallet and begin testing with the wallet just fine.

The issue arose when attempting to send a transfer from one wallet to another. The transfer succeeds as expected with the receiving wallet showing the incoming transfer and updating it's balance as expected.

However, on the "Sending" mobile device I receive an error as below;

![Imgur](https://i.imgur.com/6s64agV.jpg)

and 

![Imgur](https://i.imgur.com/jVfUmDg.jpg)

I captured the logs on the mobile device (Android) and this is what I see in the log details;

```[17:49:50] I | ReactNativeJS ▶︎ [12:49:50]: Verifying amounts of transaction

[17:49:50] I | ReactNativeJS ▶︎ [12:49:50]: Verifying transaction fee
                             └ [12:49:50]: Relaying transaction

[17:49:51] I | ReactNativeJS ▶︎ [12:49:51]: Storing sent transaction

[17:49:51] I | ReactNativeJS ▶︎ [12:49:51]: Marking sent inputs as locked
                             └ [12:49:51]: Transaction process complete.

[17:49:51] I | ReactNativeJS ▶︎ [12:49:51]: Function getTransactions called
                             └ [12:49:51]: Function getNumTransactions called

[17:49:51] I | ReactNativeJS ▶︎ [12:49:51]: Sent transaction f8cf846b2c173fc778be5c4a53c29a3388e3d8da6ead891c968010f7712e3ea5

[17:49:51] W | ReactNativeJS ▶︎ Warning: RNCNetInfo - You are using the deprecated API. It will still work, but you must upgrade to the new API to receive the new features. The old API will be removed in the future

[17:49:51] E | ReactNativeJS ▶︎ TypeError: undefined is not an object (evaluating 'this.state.error.toString')
                             │ 
                             │ This error is located at:
                             │ in ConfirmScreen (at SceneView.js:9)
                             │ in SceneView (at StackViewLayout.tsx:888)
                             │ in RCTView (at View.js:35)
                             │ in View (at StackViewLayout.tsx:887)
                             │ in RCTView (at View.js:35)
                             │ in View (at StackViewLayout.tsx:886)
                             │ in RCTView (at View.js:35)
```

From the error logs and the error screen it looks as though the issue is in the TransferScreen.js in the .src/ folder for the mobile wallet at line 880 with this statement;

```

    errorScreen() {
        let errorMessage = this.state.error.toString();

        if (this.state.error.errorCode === WalletErrorCode.NOT_ENOUGH_BALANCE) {
```
Apparently, the **this.state.error** is not properly receiving the expected promise results.
Is there a fix that I can employ to resolve this?

**Comment by zpalmtree** [comment]
As you have determined, the transaction was successfully sent. `result.success` should be true as we'll only hit this block when it is: <https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/6f364e1/lib/WalletBackend.ts#L2544-L2562>

Therefore `haveError` should be set to false here: <https://github.com/turtlecoin/turtlecoin-mobile-wallet/blob/master/src/TransferScreen.js#L841> and thus we should never render the error screen and hit the issue because the error is undefined <https://github.com/turtlecoin/turtlecoin-mobile-wallet/blob/master/src/TransferScreen.js#L1190-L1192>

Obviously this is not happening, so I would suggest printing out the result object you get from the transfer. One big red flag is that the transaction should be being *prepared*, not sent, as you see in your log. If the transaction is getting sent before hitting the confirm screen, then the `relayToNetwork` parameter is not being respected, and you could look into that issue as well.

**Comment by p2poolmining** [comment]
I was able to track this issue back to a problem within the NODE node_modules that were loaded. It seems I did not have the proper versions of all the required modules. Remove node_modules and ran ``yarn install`` and things went good from that point. 

Closing this issue.
