### ISSUE TITLE
malicicous daemon and address too long

### ISSUE THREAD

**Issue by Nash-Cash** [turtlecoin/turtlecoin-mobile-wallet#49]
that are my last errors... the Possibly malicious daemon comes some times after syncing and my addresses are 98chars long. i have changed that in the config.js. adding recipiens into the address book is working fine, but if i want to send them coins, ive got the error: The Address given is to short or to long. Are there other files where i have to change that?

**Comment by wrkzdev** [comment]
I haven't experienced that. Shall you try zedwallet with that remote node to see if it works as normal?

**Comment by zpalmtree** [comment]
If you could give the *exact* error messages, along with logs and/or screenshots, it would help.

Most likely, the daemon is doing something weird (occasionally it just returns garbage data with no rhyme nor reason) and the backend is reporting that error.

I would strongly suggest using a blockchain cache API instead. It is relatively easy to setup, faster than a daemon, will have better uptime, and won't have this issue.

Regarding the address length, I'm not sure where that would be coming from. I'll investigate at some point, but not really a high priority, feel free to trace the code yourself to propose a fix.

**Comment by zpalmtree** [comment]
The malicious daemon will no longer cause the wallet to stop syncing. Haven't had a chance to look into the transfer issue yet.

**Comment by brandonlehmann** [comment]
Can confirm that the daemon occasionally returns garbage data. The cache collection scripts account for this and don’t import data that doesn’t make sense.

**Comment by Nash-Cash** [comment]
the daemon thing is solved for the first time. but i dont't understand that address is to long problem. i only find in the config.js the address lenght. react native log android dont show me anything for that. is there an other file wich i forgett?

**Comment by zpalmtree** [comment]
It's probably somewhere in https://github.com/turtlecoin/turtlecoin-wallet-backend-js that isn't correctly getting the config passed through. Try just stepping through the code, and into the node modules, printing out `console.log` until you get to the point where it fails.

**Comment by Nash-Cash** [comment]
Ok in the turtle-wallet-backend-js folder in node-modules i found some lines with have to do with address prefix and lenght. You must know im new to this *duck* . Should i change this?

**Comment by zpalmtree** [comment]
Yeah, hardcoding it could fix the issue, but it's not really the best way to do it. If you step through where the code goes, you should be able to figure out why it's broken, just by printing to the console until it breaks.

**Comment by Nash-Cash** [comment]
I blame myself. how do I print that out?

**Comment by zpalmtree** [comment]
Open up the code, add something like `console.log('1');`, in the transfer function, do that every few lines, until one of your numbers doesn't get printed due to the error - now you know roughly which line it crashes on - keep going down the callstack until you find the exact line that causes the crash.

Once you've done that, you can probably print out the variables that are being used to see what is happening, maybe the config value isn't 98 like you expect it is, maybe the address is not the same.

**Comment by Nash-Cash** [comment]
somehow I'm too stupid to do that: add something like console.log('1') :o) . I read me deeper into the code and excluded validate address lenght (turtlecoin-wallet-backend-js/dist/lib/ValidateParameters.js). but that gave me a prefix error, which suggests that the outputs are all TRTL and I have to change that in the node modules ?

**Comment by zpalmtree** [comment]
Ok..

I just tested. Changed my address prefix, and address length, I used a monero address to test (address prefix: 12, address length: 95). The transaction failed because I was using an existing wallet, so it was taking my TurtleCoin address as the change address, which is obviously not a valid XMR address.

After just generating a new wallet, my primary address was now an XMR address, and sending to an XMR address succeeded.

So.. just delete your wallet, and make a new one, and see if it works then.

If this helps, this is how I was debugging it:

```js
function validateTransaction(destinations, mixin, fee, paymentID, subWalletsToTakeFrom, changeAddress, currentHeight, subWallets) {
    console.log('2');
    /* Validate the destinations are valid */
    let error = ValidateParameters_1.validateDestinations(destinations);
    if (!_.isEqual(error, WalletError_1.SUCCESS)) {
        return error;
    }
    console.log('3');
    /* Validate stored payment ID's in integrated addresses don't conflict */
    error = ValidateParameters_1.validateIntegratedAddresses(destinations, paymentID);
    if (!_.isEqual(error, WalletError_1.SUCCESS)) {
        return error;
    }
    console.log('4');
    /* Verify the subwallets to take from exist */
    error = ValidateParameters_1.validateOurAddresses(subWalletsToTakeFrom, subWallets);
    if (!_.isEqual(error, WalletError_1.SUCCESS)) {
        return error;
    }
    console.log('5');
```

Just add some print statements, then watch the log with `react-native log-android` and find where the printing stops. In this case, it printed '4' but not '5', so I knew it was the `validateOurAddresses` function which was failing. Then I stepped into that function and figured out what's going wrong with the same method, etc, until you find the issue.

**Comment by Nash-Cash** [comment]
I tried that the way you wrote it. As a mistake I get that:

 console.log('1');
    /* Validate the destinations are valid */
    let error = ValidateParameters_1.validateDestinations(destinations);
    if (!_.isEqual(error, WalletError_1.SUCCESS)) {
        return error;

but if I go any further I'll come to this: 

function validateDestinations(destinations) {
    if (destinations.length === 0) {
        return new WalletError_1.WalletError(WalletError_1.WalletErrorCode.NO_DESTINATIONS_GIVEN);
    }
    const destinationAddresses = [];
    for (const [destination, amount] of destinations) {
        if (amount === 0) {
            return new WalletError_1.WalletError(WalletError_1.WalletErrorCode.AMOUNT_IS_ZERO);
        }
        if (amount < 0) {
            return new WalletError_1.WalletError(WalletError_1.WalletErrorCode.NEGATIVE_VALUE_GIVEN);
        }
        if (!Number.isInteger(amount)) {
            return new WalletError_1.WalletError(WalletError_1.WalletErrorCode.NON_INTEGER_GIVEN);
        }
        destinationAddresses.push(destination);
    }
    /* Validate the addresses, integrated addresses allowed */
    return validateAddresses(destinationAddresses, true);
}

i tried everywhere to find and understand the error: address given to longh or to short. i then came to the config.js in the modules folder and changed the parameters (99 to 98), but the error stays. I don't know any help anymore :-(

**Comment by zpalmtree** [comment]
Can you post 
* Your address prefix in the config
* Your address length in the config
* Your wallet address you are testing with
* The wallet address you are trying to send to

**Comment by Nash-Cash** [comment]
0x5bc80 (NaCa)

98

NaCaaKLMtSnCEqmHQghu3rgsQrf66mMj8QH6qtak8ithMPa77q3KuevVmQzPoNFn6rYZhrq9CqVuSY9nUNVyL3831mAHcyfC7X (This is the generatet wallet address. sending coins to that works fine)

NaCatBdB4qbZC3BT8myDSJJNgDW2gwSYwCJGzPjchJnm3Bo78WW5yAm66a87ssX51KW4HcsYQTbiHearTn4wYgxX5q3zGn37j3 (This is one Payee address. But i testet more than that one)

I want to say thank you for taking so much time for me.

**Comment by zpalmtree** [comment]
Sorry, forgot about this.

I tried using your config, and was able to send a transaction to the address you could not send to. I created a new wallet, to ensure my change address was valid. Did you change the dev fee address? That's the only thing I could think that is causing it to fail, since that is a TurtleCoin address.

If that's not the case, I would suggest reforking the repo, and making one change at a time to find out what is causing the error. For reference, here are the changes I made to test:

```diff
diff --git a/src/Config.js b/src/Config.js
index 585d210..abdd348 100644
--- a/src/Config.js
+++ b/src/Config.js
@@ -39,7 +39,7 @@ const Config = {
      * The address prefix your coin uses - you can find this in CryptoNoteConfig.h.
      * In TurtleCoin, this converts to TRTL
      */
-    addressPrefix: 3914525,
+    addressPrefix: 0x5bc80,
 
     /**
      * Request timeout for daemon operations in milliseconds
@@ -106,7 +106,7 @@ const Config = {
     /**
      * The length of a standard address for your coin
      */
-    standardAddressLength: 99,
+    standardAddressLength: 98,
 
     /**
      * The length of an integrated address for your coin - It's the same as
@@ -115,7 +115,7 @@ const Config = {
      * chunks of 8 chars at once into blocks of 11 chars, we can calculate
      * this automatically
      */
-    integratedAddressLength: 99 + ((64 * 11) / 8),
+    integratedAddressLength: 98 + ((64 * 11) / 8),
 
     /**
      * Use our native func instead of JS slowness
```

**Comment by Nash-Cash** [comment]
was my mistake.. i used an old dev fee address :-(

thank you very much
