### ISSUE TITLE
Transaction address

### ISSUE THREAD

**Issue by afterconnery** [turtlecoin/turtlecoin-mobile-wallet#53]
Would it be possible to add the contact to the details of the transactions on the transaction page? Currently I have to try and  remember who I sent TRTL to because the contact isnt part of the transaction log  details.

**Comment by zpalmtree** [comment]
We could store this client side, however it would be lost when reimporting the wallet. I'm not sure if the inconsistency is worth it...

Probably not *too* tricky to do, but we would also have to modify the database format.

**Comment by afterconnery** [comment]
I read the blog post earlier, good interview btw, and I wanted to explore more of the wallet to check things out. Inconsistency isnt worth it imo. Would a memo space be difficult to add? Maybe that would do the trick for me personally. Its just an idea.

**Comment by zpalmtree** [comment]
Do you mean allow adding a comment, via the 'Transaction Details' screen? If so, that wouldn't be too hard (and we could add that via the send transaction screen as well, I suppose, which would be a little more intuitive)

I don't actually think your idea would be bad, there are already optional fields there, like payment ID, so putting the address / payee name wouldn't be that bad.

Thinking about it now, it would be easy enough to just have a separate DB, mapping transaction hashes to messages/address/payee names, rather than altering the main DB.

**Comment by afterconnery** [comment]
I was thinking about adding a field in the send transaction screen.

**Comment by zpalmtree** [comment]
The issue with that is that if we scan a QR code that has all the necessary info, it takes us straight to the confirm screen, so no time to add a memo, unless we want to add additional steps, which I'm not a fan of.

I'm going to see how it looks to add the recipient + address to the transactions we sent, and maybe add an optional memo field there to be filled in later.

Actually... maybe we could add a memo field on the confirm screen - we could use a similar 'change' button to toggle a field, as we did on the modify payee screen.

**Comment by zpalmtree** [comment]
Done: 
![image](https://user-images.githubusercontent.com/22151537/54716023-b3580a80-4b4c-11e9-990d-52ff86a83732.png)

You can add a memo on the transactions screen, address + recipient are saved automatically.

**Comment by afterconnery** [comment]
I am excited for the new release! Thanks again for your work!
