### ISSUE TITLE
Fingerprint support

### ISSUE THREAD

**Issue by tatarenko** [turtlecoin/turtlecoin-mobile-wallet#66]
Please add fingerprint support to unlock wallet without PIN.

**Comment by zpalmtree** [comment]
This is not possible unfortunately. We use the pincode to encrypt your wallet on disk, otherwise other apps would be able to access your wallet data. Since the fingerprint libraries I can see only really give a binary 'valid/invalid' result, we can't get an encryption key from this.

Possibly if you had a lower level library or built your own you could get pick out an encryption key from a fingerprint somehow..., but I don't see one of these for react-native.

**Comment by tatarenko** [comment]
What about this 2?
https://github.com/Mauin/RxFingerprint
https://github.com/infinum/Android-Goldfinger
They both claim that they could encrypt/decrypt passwords through Android Keystore (https://developer.android.com/training/articles/keystore.html). So you could 
1) encrypt PIN when it setted by user
2) put it into file/database encrypted
3) Ask user auth like "Please enter PIN or just finger the sensor"
4) If user put finger to sensor, try decrypt PIN and if success, decrypt wallet with decrypted PIN, if success, open wallet without PIN

**Comment by zpalmtree** [comment]
These are both android libraries rather than react-native libraries. If you can find a similar solution for react-native, then I will look into it.

**Comment by tatarenko** [comment]
Ok, please look at this:
https://github.com/oblador/react-native-keychain
Also, find article about it: https://medium.com/react-native-training/securing-your-react-native-app-using-keychain-6de10850d203

**Comment by tatarenko** [comment]
Also this one
https://github.com/cgomezmendez/react-native-biometrics

**Comment by zpalmtree** [comment]
Thank you for the links, I will see if I can implement it for >= 0.0.9

**Comment by brandonlehmann** [comment]
@tatarenko you're like halfway there... keep working and get to 100% and submit a PR :)

**Comment by tatarenko** [comment]
@brandonlehmann My programming skills incompatible with android, sorry

**Comment by zpalmtree** [comment]
This would be pretty easy to do now since we changed databases

**Comment by zpalmtree** [comment]
Done
