### ISSUE TITLE
App hangs

### ISSUE THREAD

**Issue by tatarenko** [turtlecoin/turtlecoin-mobile-wallet#70]
App hangs after some time

I just open app, see it sync, waiting for like 2 minutes and then sync process stops, can't change tab.

**Environment**
- App version: 0.0.8
- Android version: 9
- Phone model: Xiaomi A2 Lite

**Comment by zpalmtree** [comment]
Hiya,

This is due to the DB compacting in the background, to try and alleviate the file size issues laid out in #68
The compaction takes quite some time depending on your wallet size, so I schedule it once every 2 days, preferably in the background
However, if it has never been done in the background, it will occur after 2 minutes in the foreground.
It *should* eventually complete, but it's possible the compaction fails and it doesn't unfreeze.

This should shortly be fixed when I fix the underlying issue #68

**Comment by zpalmtree** [comment]
Will be fixed in next version, compaction is no longer performed.
